_metadata:
  major_version: 1
  minor_version: 1

display_information:
  name: Slack Mirror (Dedicated Socket Mode)
  description: Private dedicated Slack Mirror app using Socket Mode
  background_color: "#1D9BF0"

features:
  app_home:
    home_tab_enabled: false
    messages_tab_enabled: false
    messages_tab_read_only_enabled: true
  bot_user:
    display_name: Slack Mirror
    always_online: false
  slash_commands: []

oauth_config:
  redirect_urls: []
  scopes:
    bot:
      - app_mentions:read
      - channels:history
      - channels:read
      - chat:write
      - files:read
      - groups:history
      - groups:read
      - im:history
      - im:read
      - mpim:history
      - mpim:read
      - users:read
    user:
      - channels:history
      - channels:read
      - groups:history
      - groups:read
      - im:history
      - im:read
      - mpim:history
      - mpim:read
      - search:read.public
      - search:read.mpim
      - users:read

settings:
  event_subscriptions:
    bot_events:
      - app_mention
      - message.channels
      - message.groups
      - message.im
      - message.mpim
  interactivity:
    is_enabled: false
  org_deploy_enabled: false
  socket_mode_enabled: true
  token_rotation_enabled: false
