#!/usr/bin/env bash
set -euo pipefail

# User-scope install/update/uninstall for slack-mirror in an isolated environment.
#
# Goals:
# - Install current repo contents into a user-owned app dir
# - Keep runtime independent from this working tree
# - Preserve config + DB across updates
# - Run DB migrations on install/update
#
# Usage:
#   scripts/user_env.sh install
#   scripts/user_env.sh update
#   scripts/user_env.sh uninstall [--purge-data]
#   scripts/user_env.sh status

CMD="${1:-}"
shift || true

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_ROOT="${HOME}/.local/share/slack-mirror"
APP_DIR="${APP_ROOT}/app"
VENV_DIR="${APP_ROOT}/venv"
LEGACY_STATE_DIR="${APP_ROOT}/var"
STATE_DIR="${XDG_STATE_HOME:-${HOME}/.local/state}/slack-mirror"
CACHE_DIR="${XDG_CACHE_HOME:-${HOME}/.local/cache}/slack-mirror"
CONFIG_DIR="${HOME}/.config/slack-mirror"
BIN_DIR="${HOME}/.local/bin"
CONFIG_PATH="${CONFIG_DIR}/config.yaml"
ENV_PATH="${CONFIG_DIR}/env.sh"
WRAPPER_PATH="${BIN_DIR}/slack-mirror-user"

mkdir -p "${BIN_DIR}" "${CONFIG_DIR}" "${STATE_DIR}" "${CACHE_DIR}"

log() { printf "[%s] %s\n" "$(date +'%H:%M:%S')" "$*"; }

die() { echo "ERROR: $*" >&2; exit 1; }

need_bin() {
  command -v "$1" >/dev/null 2>&1 || die "required command missing: $1"
}

write_env_file() {
  cat > "${ENV_PATH}" <<EOF
# Generated by scripts/user_env.sh
export SLACK_MIRROR_DB="${STATE_DIR}/slack_mirror.db"
export SLACK_MIRROR_CACHE="${CACHE_DIR}"
EOF
}

migrate_legacy_state() {
  local legacy_db="${LEGACY_STATE_DIR}/slack_mirror.db"
  local legacy_cache="${LEGACY_STATE_DIR}/cache"
  local target_db="${STATE_DIR}/slack_mirror.db"

  if [[ ! -f "${target_db}" && -f "${legacy_db}" ]]; then
    log "migrating legacy DB into stable state dir: ${target_db}"
    cp -a "${legacy_db}" "${target_db}"
  fi

  if [[ ! -d "${CACHE_DIR}" || -z "$(find "${CACHE_DIR}" -mindepth 1 -maxdepth 1 2>/dev/null | head -n 1)" ]]; then
    if [[ -d "${legacy_cache}" ]]; then
      log "migrating legacy cache into stable cache dir: ${CACHE_DIR}"
      mkdir -p "${CACHE_DIR}"
      cp -a "${legacy_cache}/." "${CACHE_DIR}/"
    fi
  fi
}

copy_repo_snapshot() {
  need_bin rsync
  mkdir -p "${APP_DIR}"
  rsync -a --delete \
    --exclude '.git/' \
    --exclude '.venv/' \
    --exclude '.pytest_cache/' \
    --exclude '__pycache__/' \
    --exclude 'cache/' \
    --exclude 'localhost+*.pem' \
    --exclude '.openclaw/' \
    "${REPO_ROOT}/" "${APP_DIR}/"
}

ensure_venv() {
  if [[ ! -x "${VENV_DIR}/bin/python" ]]; then
    need_bin python3
    log "creating venv: ${VENV_DIR}"
    python3 -m venv "${VENV_DIR}"
  fi
  "${VENV_DIR}/bin/pip" install --upgrade pip wheel setuptools >/dev/null
}

install_python_package() {
  log "installing package into venv"
  "${VENV_DIR}/bin/pip" install --upgrade "${APP_DIR}" >/dev/null
}

ensure_config() {
  if [[ ! -f "${CONFIG_PATH}" ]]; then
    log "creating config from template: ${CONFIG_PATH}"
    cp "${APP_DIR}/config.example.yaml" "${CONFIG_PATH}"
  fi
  cp "${APP_DIR}/config.example.yaml" "${CONFIG_DIR}/config.example.latest.yaml"
}

write_wrapper() {
  cat > "${WRAPPER_PATH}" <<EOF
#!/usr/bin/env bash
set -euo pipefail
source "${ENV_PATH}"
exec "${VENV_DIR}/bin/slack-mirror" --config "${CONFIG_PATH}" "\$@"
EOF
  chmod +x "${WRAPPER_PATH}"
}

run_migrations() {
  log "running schema migrations (mirror init)"
  "${WRAPPER_PATH}" mirror init
  log "syncing workspace definitions"
  "${WRAPPER_PATH}" workspaces sync-config
}

install_cmd() {
  log "installing isolated user environment"
  write_env_file
  copy_repo_snapshot
  ensure_venv
  install_python_package
  ensure_config
  migrate_legacy_state
  write_wrapper
  run_migrations
  log "install complete"
  echo
  echo "CLI wrapper: ${WRAPPER_PATH}"
  echo "Config:      ${CONFIG_PATH}"
  echo "State dir:   ${STATE_DIR}"
  echo "Cache dir:   ${CACHE_DIR}"
  echo
  echo "Next: edit config and run:"
  echo "  ${WRAPPER_PATH} workspaces verify"
}

update_cmd() {
  log "updating isolated user environment from current repo"
  [[ -f "${ENV_PATH}" ]] || write_env_file
  copy_repo_snapshot
  ensure_venv
  install_python_package
  ensure_config
  migrate_legacy_state
  write_wrapper
  run_migrations
  log "update complete (config + DB preserved)"
  echo "Latest config template saved at: ${CONFIG_DIR}/config.example.latest.yaml"
}

uninstall_cmd() {
  local purge_data="false"
  if [[ "${1:-}" == "--purge-data" ]]; then
    purge_data="true"
  fi

  log "stopping/removing user services if present"
  systemctl --user disable --now slack-mirror-webhooks.service slack-mirror-events.service slack-mirror-embeddings.service 2>/dev/null || true
  rm -f "${HOME}/.config/systemd/user/slack-mirror-webhooks.service" \
        "${HOME}/.config/systemd/user/slack-mirror-events.service" \
        "${HOME}/.config/systemd/user/slack-mirror-embeddings.service"
  systemctl --user daemon-reload || true

  log "removing wrapper + app + venv"
  rm -f "${WRAPPER_PATH}"
  rm -rf "${APP_DIR}" "${VENV_DIR}"

  if [[ "${purge_data}" == "true" ]]; then
    log "purging config + data"
    rm -rf "${CONFIG_DIR}" "${STATE_DIR}" "${CACHE_DIR}"
  else
    log "preserving config + data"
  fi

  log "uninstall complete"
}

status_cmd() {
  echo "Wrapper:  ${WRAPPER_PATH}"
  if [[ -x "${WRAPPER_PATH}" ]]; then
    echo "  status: present"
  else
    echo "  status: missing"
  fi
  echo "Config:   ${CONFIG_PATH}"
  [[ -f "${CONFIG_PATH}" ]] && echo "  status: present" || echo "  status: missing"
  echo "DB:       ${STATE_DIR}/slack_mirror.db"
  [[ -f "${STATE_DIR}/slack_mirror.db" ]] && echo "  status: present" || echo "  status: missing"
  echo "Cache:    ${CACHE_DIR}"
  [[ -d "${CACHE_DIR}" ]] && echo "  status: present" || echo "  status: missing"
  echo "Services:"
  systemctl --user --no-pager --full status slack-mirror-webhooks.service slack-mirror-events.service slack-mirror-embeddings.service 2>/dev/null | sed -n '1,30p' || true
}

case "${CMD}" in
  install) install_cmd ;;
  update) update_cmd ;;
  uninstall) uninstall_cmd "${1:-}" ;;
  status) status_cmd ;;
  *)
    cat <<EOF
Usage:
  scripts/user_env.sh install
  scripts/user_env.sh update
  scripts/user_env.sh uninstall [--purge-data]
  scripts/user_env.sh status
EOF
    exit 1
    ;;
esac
